name: Mega Auto Scraper 2026

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: write

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set Node Version Env
      run: echo "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true" >> $GITHUB_ENV

    - name: Install dependencies & Playwright Browsers
      run: |
        pip install playwright beautifulsoup4 pandas
        playwright install chromium
        playwright install-deps chromium

    - name: Run Scraper Bot
      run: python mega_scraper.py

    - name: Commit and Push Big Data
      run: |
        git config --global user.name "Mega Data Bot"
        git config --global user.email "databot@github.com"
        git add data/* || true
        git commit -m "Scraped All Mobile Tabs Safely" || exit 0
        git push
